type stringKey = Record<string, string>

export const provinceMap: stringKey = {
	北京市: 'beijing',
	天津市: 'tianjin',
	上海市: 'shanghai',
	重庆市: 'chongqing',
	河北省: 'hebei',
	山西省: 'shanxi',
	辽宁省: 'liaoning',
	吉林省: 'jilin',
	黑龙江省: 'heilongjiang',
	江苏省: 'jiangsu',
	浙江省: 'zhejiang',
	安徽省: 'anhui',
	福建省: 'fujian',
	江西省: 'jiangxi',
	山东省: 'shandong',
	河南省: 'henan',
	湖北省: 'hubei',
	湖南省: 'hunan',
	广东省: 'guangdong',
	海南省: 'hainan',
	四川省: 'sichuan',
	贵州省: 'guizhou',
	云南省: 'yunnan',
	陕西省: 'shaanxi',
	甘肃省: 'gansu',
	青海省: 'qinghai',
	台湾省: 'taiwan',
	内蒙古自治区: 'neimenggu',
	广西壮族自治区: 'guangxi',
	西藏自治区: 'xizang',
	宁夏回族自治区: 'ningxia',
	新疆维吾尔自治区: 'xinjiang'
}

export const guangdongMap: stringKey = {
	广州市: 'guangzhou',
	深圳市: 'shenzhen',
	珠海市: 'zhuhai',
	佛山市: 'foshan',
	中山市: 'zhongshan',
	惠州市: 'huizhou',
	汕头市: 'shantou',
	江门市: 'jiangmen',
	湛江市: 'zhanjiang',
	肇庆市: 'zhaoqing',
	梅州市: 'meizhou',
	茂名市: 'maoming',
	阳江市: 'yangjiang',
	清远市: 'qingyuan',
	韶关市: 'shaoguan',
	揭阳市: 'jieyang',
	汕尾市: 'shanwei',
	潮州市: 'chaozhou',
	河源市: 'heyuan',
	云浮市: 'yunfu'
}
